default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  adapter: sqlite3

test:
  <<: *default
  database: db/test.sqlite3
  adapter: sqlite3

production:
  <<: *default
